### ISSUE TITLE
Feature Request: logfiles for fail2ban with loglog

### ISSUE THREAD

**Issue by ni-kw** [wilminator/dokuwiki-plugin-twofactor#15]
I want to use fail2ban. There is a good plugin "Login/Logoff Logging Plugin" I could use.
https://www.dokuwiki.org/plugin:loglog

With the Two Factor Google Authenticator enabled I get entries in the logfile for successful login and logout - but not for faild attempts.

You may are able to add support for the plugin:
![grafik](https://user-images.githubusercontent.com/16056721/42269599-d8e32b6c-7f7e-11e8-9679-f44afa89c259.png)

**Comment by wilminator** [comment]
I have just released this feature with Loglog.  Please try it out and confirm.

**Comment by ni-kw** [comment]
Sorry for the late test.
I've testet to login with the user "test.without-token", only typed in a user and a password (1).
And then tested to login with the user "test.with-token", typed in a user a password and a OTP (2).
I did both tests only one time. This is what I found in the log:
![grafik](https://user-images.githubusercontent.com/16056721/42984958-8d3b86f0-8bef-11e8-8a1f-0dfac5eb79ab.png)

**Comment by ni-kw** [comment]
A correct login and logout looks like this:
![grafik](https://user-images.githubusercontent.com/16056721/42985107-4cda5cc0-8bf0-11e8-82f3-974b3819c748.png)

So I can set a filter looking for "OTP" in the logfile. Not perfect but I think it could work :)

Logfile
<code>
1532064723      2018/07/20 05:32        10.10.1.254     test.without-token      logged in, requires OTP code
1532064723      2018/07/20 05:32        10.10.1.254     test.without-token      logged in, requires OTP code
1532064740      2018/07/20 05:32        10.10.1.254     test.with-token failed token login, no tokens configured
1532064740      2018/07/20 05:32        10.10.1.254     test.with-token logged in, requires OTP code
1532064740      2018/07/20 05:32        10.10.1.254     test.with-token logged in, requires OTP code
1532065121      2018/07/20 05:38        10.10.1.254     userx   logged in using correct token
1532065121      2018/07/20 05:38        10.10.1.254     userx   logged in temporarily
1532065152      2018/07/20 05:39        10.10.1.254     userx   logged off
</code>

**Comment by wilminator** [comment]
What I tried to do was provide the original loglog functionality, with the context of two factor authentication.  That said:
"logged in using correct token" means the user entered a correct password and a correct token, and and was logged in without any additional intervention.
"logged in, requires OTP code" is the one you should be concerned about.  This means that the user knows the password to the account.
"Failed token login" in any context means that the user supplied an incorrect token.  The "no tokens configured" warning should be carefully looked at; I would expect that a user would know if they have a token and more than one log in a minute is likely an attack.
There is also a "Logged out, user quit OTP"  This is when the user chooses to quit trying to log in the second time.  Technically, they did log into the wiki with the first password.  You may want to set an alert if this happens, because it means that account password is known and someone chose to not follow through with the second login.

There should be the usual "bad password". "logged in", and "logged out" entries from the original loglog.  I took care to move the original "logged in" entry until AFTER the user has successfully completed two factor authentication.  You should be able to use this as a counter reset or a hacker success flag.

I did provide international language strings for the items there.  If you would be willing to translate the strings, I would be willing to add it.  The words 'logged off', 'logged in', and 'failed' cannot be changed or the loglog report icons will not work, but any text after that supports language changing.  I would appreciate any help you would be willing to provide.

Last, there is an audit file.  It compliments the loglog tracking by recording when a person successfully uses 2FA.  In Audit+ mode, it also tracks when the user changes 2FA settings and when notifications are sent using 2FA.  Not helpful with fail2ban, but might help if you need to check if a user's 2FA settings are removed.

**Comment by ni-kw** [comment]
Hi here are some translations. First one is a translation of what the message realy is. The second (if exist) is a translation near to your orignal.

logged in using correct token
=> Angemeldet mit korrektem Passwort und korrektem Token
=> angemeldet mit korrekten Token

Failed token login
=> Anmeldeversuch mit falschem Token
=> Fehlgeschlagener Token Login

failed token login, no token match
=> Fehlgeschlagener Token Login, falscher Token

logged in, requires OTP code
=> Anmeldeversuch mit korrektem Passwort, benötigt OTP code
=> angemeldet, benötigt OTP-Code

no tokens configured
=>I'm not sure about this one. This comes up when I have not configured a OTP and still try to log in in some way?

Logged out, user quit OTP
=> Abgemeldet, OTP abgebrochen

**Comment by ni-kw** [comment]
Yes :)

**Comment by wilminator** [comment]
no tokens configured
=>I'm not sure about this one. This comes up when I have not configured a
OTP and still try to log in in some way?

I'm writing this to help others understand how 2FA works.  If you already
knew this, then don't pay me any attention.

You will see this error if you supply a token value on the first login page
but have no tokens attached to the account.

There are two types of 2FA handled by this module- tokens and one time
passwords (OTP).

A token is a device that generates a time-specific value that you supply.
Google Authenticator is a token authentication app- you supply the number
on it when you login.

The one time password is created and sent to you by the wiki when you
successfully login.  If you do not supply a token code, it is assumed that
you want a one time password.

The token is more secure, because even if you know the account password,
the wiki will "play dumb" and deny your login until a proper token code is
supplied. However, if even one OTP is enabled for the user, the wiki
assumes that you want the code sent to you.  This enables hackers to get
your password, even if they cannot login.  It is the main reason I wanted
to add this logging function; now a wiki admin can use fail2ban to protect
their wiki from a brute-force password attack, closing this loop.

I have a friend at work that speaks fluent German.  I will ask her to help
me translate the rest of the text and get a full German translation into
the module. ;)
